title: Victus # site title
description: A Jekyll theme # description added to the head

name: Victus

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com